# Generated by Django 3.0.8 on 2020-10-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='image',
            field=models.ImageField(default='C:\\Users\\mrdlc\\Desktop\\portfolio\\portfolio\\index\\ytl.jpg', height_field=300, upload_to='', width_field=150),
        ),
    ]
