# Generated by Django 3.1.4 on 2020-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201007_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='image',
            field=models.CharField(default='https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png', max_length=500),
        ),
    ]
