# Generated by Django 3.2.3 on 2022-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201229_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mindes', models.TextField(max_length=600)),
                ('image', models.ImageField(upload_to='index\\static\\media')),
                ('by', models.TextField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='descreption',
        ),
    ]
