# Generated by Django 3.2.3 on 2022-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='urls',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
