# Generated by Django 3.2.3 on 2022-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_repo_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
