# Generated by Django 3.2.3 on 2022-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_certificate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogslinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('mindes', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
