# Generated by Django 3.2.3 on 2022-12-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_blogslinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogslinks',
            name='file',
        ),
    ]
