# Generated by Django 3.2.3 on 2022-12-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_blogslinks_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogslinks',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
